# Kubernetes pod with dangerous network settings - SHOULD TRIGGER ALERTS

apiVersion: v1
kind: Pod
metadata:
  name: dangerous-pod
spec:
  # Host network exposes all container ports directly
  hostNetwork: true
  
  containers:
  - name: app
    image: myapp:latest
    ports:
    - containerPort: 8080
      # hostPort exposes directly on node
      hostPort: 8080
    - containerPort: 9090
      hostPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: exposed-service
spec:
  type: LoadBalancer
  # Allowing traffic from anywhere
  loadBalancerSourceRanges:
    - 0.0.0.0/0
  ports:
  - port: 80
    targetPort: 8080
